title: Oliver Sild – Cyber-security & open-source entrepreneur
logo:  # you can add own logo.
description: Entrepreneur, passionate about cyber-security & open-source technologies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: Oliver Sild
  image: '/assets/img/profile.gif'
  job: "Oliver Sild"
  bio: Entrepreneur, passionate about cyber-security & open-source technologies.
  email: gmail@oliversild.com


# Contact links
contact:
  - name: Twitter
    link: https://twitter.com/oliversild
  - name: Linkedin
    link: https://www.linkedin.com/in/oliversild/
#  - name: Instagram
#    link: https://instagram.com/


# Comment Section (Disqus)
disqus-identifier: # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics: UA-180865850-1

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
